name: CI
on:
    push:
    pull_request:
    workflow_run:
        workflows: ["Update DT Commits"]
        types:
            - completed
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["20", "22"]
        name: Node ${{ matrix.node }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}
            - name: Install
              run: npm install
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test
            - name: Lint
              run: npm run lint
