name: Update DT Commits

on:
    # Weekly on Sunday at 00:00 UTC
    schedule:
        - cron: "0 0 * * 0"

    # Or execute manually from UI
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/checkout@v4
              with:
                  repository: DefinitelyTyped/DefinitelyTyped
                  path: tmp/DefinitelyTyped
                  fetch-depth: 0
                  # We don't actually need anything but the commit history
                  sparse-checkout: README.md

            - name: Update DT Commits
              run: ./scripts/update_dt_history.sh

            - name: Commit DT Updates
              run: |
                  git config --local user.email "github-actions@github.com"
                  git config --local user.name "github-actions"
                  ./scripts/commit_dt_history.sh
